In [16]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Clasiification Tasks

## One Example

<div dir='rtl'>📊 תרחיש:
נניח שיש לנו נתונים של אנשים עם שני משתנים:

גיל

שעות פעילות ספורט בשבוע

המטרה היא לחזות האם האדם בריא (1) או לא בריא (0), לפי ההנחות הבאות:

אדם שעושה לפחות 3 שעות ספורט בשבוע והוא צעיר מ־50 -> נחשב בריא.

אחרת -> לא בריא.

</div>

In [3]:
data = {
    'age':       [25, 45, 52, 23, 63, 33, 40, 29, 61, 48],
    'sport_hrs': [5, 2, 1, 4, 0, 3, 2, 6, 0, 1],
    'healthy':   [1, 0, 0, 1, 0, 1, 0, 1, 0, 0]  # Label
}

In [4]:
df = pd.DataFrame(data)
df.head()

age  sport_hrs  healthy
0   25          5        1
1   45          2        0
2   52          1        0
3   23          4        1
4   63          0        0

In [5]:
features = df[['age','sport_hrs']]
labal = df['healthy']

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(features,labal,test_size=0.2,random_state=42)


5    1
0    1
7    1
2    0
9    0
4    0
3    1
6    0
Name: healthy, dtype: int64

In [13]:
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [14]:
y_pred = model.predict(x_test)
y_pred

array([0, 0], dtype=int64)

In [17]:
accuracy_score(y_test,y_pred)

1.0

In [22]:
new_value = [[28,4]]
pred_new_value = model.predict(new_value)
pred_new_value

c:\Users\USER001\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

## Example 2

<div dir='rtl'>📘 תרחיש: חיזוי סוכרת (Diabetes Prediction)
נשתמש במערך נתונים שנקרא Pima Indians Diabetes Dataset דרך sklearn (אפשר גם דרך pandas מ־CSV, אם תרצה).

המטרה: לחזות האם לאישה יש סוכרת (1) או לא (0) לפי מדדים רפואיים בסיסיים.

🔢 משתנים עיקריים:
Pregnancies: מספר הריונות

Glucose: רמת סוכר בדם

BloodPressure: לחץ דם

BMI: מדד מסת גוף

Age: גיל

...ועוד</div>

In [23]:
from sklearn.datasets import fetch_openml

In [26]:
data = fetch_openml(name='diabetes', version=1, as_frame=True)
df = data.frame
df.head()

preg  plas  pres  skin  insu  mass   pedi  age            class
0     6   148    72    35     0  33.6  0.627   50  tested_positive
1     1    85    66    29     0  26.6  0.351   31  tested_negative
2     8   183    64     0     0  23.3  0.672   32  tested_positive
3     1    89    66    23    94  28.1  0.167   21  tested_negative
4     0   137    40    35   168  43.1  2.288   33  tested_positive

In [27]:
df['class'].value_counts()

class
tested_negative    500
tested_positive    268
Name: count, dtype: int64

In [29]:
features = df.drop(columns=['class'])
label = df['class'].apply(lambda x: 1 if x == 'tested_negative' else 0)
labal

0    1
1    0
2    0
3    1
4    0
5    1
6    0
7    1
8    0
9    0
Name: healthy, dtype: int64

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(features,label,test_size=0.2,random_state=42)


(614, 154)

In [33]:
model = LogisticRegression()
model.fit(x_train,y_train)


c:\Users\USER001\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [35]:
y_pred = model.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1],
      dtype=int64)

In [42]:
accuracy_score(y_test,y_pred)*100

74.67532467532467

## Example 3

<div dir='rtl'>📘 תרחיש: סיווג סוג פרח לפי מאפיינים פיזיים
נשתמש במערך הנתונים הקלאסי והמעשי מאוד: Iris Dataset
זהו בסיס נתונים שמשמש הרבה בלימוד של סיווג מרובה מחלקות.

🎯 מטרה:
לחזות את סוג הפרח (setosa, versicolor, virginica) על פי מאפיינים מדודים:

sepal length (אורך גביע)

sepal width (רוחב גביע)

petal length (אורך עלי כותרת)

petal width (רוחב עלי כותרת)

סה"כ 3 מחלקות לסיווג ⇒ Multiclass</div>

In [45]:
from sklearn.datasets import load_iris

In [52]:
iris = load_iris()


In [55]:
X = iris.data
df = pd.DataFrame(X)
df.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [56]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [57]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=24)
len(x_train),len(x_test)

(120, 30)

In [58]:
model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=200)
model.fit(x_train,y_train)

c:\Users\USER001\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=200, multi_class='multinomial')

In [60]:
y_pred = model.predict(x_test)
accuracy_score(y_test,y_pred)*100

100.0

In [41]:
acc = (y_pred==y_test).sum()
acc = acc/y_test.shape[0]
acc*100

74.67532467532467

## Example 4

<div dir='rtl'>🛒 תרחיש: חיזוי קטגוריית מוצר לפי מאפיינים
🎯 מטרה:
לחזות לאיזו קטגוריה שייך מוצר (למשל: ביגוד, אלקטרוניקה, מזון) לפי מאפיינים כמותיים.

📦 מאפייני המוצר:
weight: משקל המוצר בגרמים

price: מחיר המוצר בש"ח

fragile: האם המוצר שביר (1 = כן, 0 = לא)

brand_score: דירוג המותג בין 1–10

🎯 תווית היעד (label):
0 = ביגוד

1 = אלקטרוניקה

2 = מזון<div>

In [61]:
data = {
    'weight':      [500, 1500, 200, 100, 1200, 300, 700, 50, 80, 250],
    'price':       [200, 1500, 20, 10, 900, 60, 350, 5, 7, 40],
    'fragile':     [0, 1, 0, 0, 1, 0, 1, 0, 0, 0],
    'brand_score': [6, 9, 5, 4, 8, 6, 7, 3, 4, 5],
    'category':    [0, 1, 2, 2, 1, 0, 1, 2, 2, 0]  # 0=bגוד, 1=אלקטרוניקה, 2=מזון
}


In [62]:
df = pd.DataFrame(data)
df.head()

weight  price  fragile  brand_score  category
0     500    200        0            6         0
1    1500   1500        1            9         1
2     200     20        0            5         2
3     100     10        0            4         2
4    1200    900        1            8         1

In [67]:
X = df.drop(columns=['category'])
y = df['category']
X,y

(   weight  price  fragile  brand_score
 0     500    200        0            6
 1    1500   1500        1            9
 2     200     20        0            5
 3     100     10        0            4
 4    1200    900        1            8
 5     300     60        0            6
 6     700    350        1            7
 7      50      5        0            3
 8      80      7        0            4
 9     250     40        0            5,
 0    0
 1    1
 2    2
 3    2
 4    1
 5    0
 6    1
 7    2
 8    2
 9    0
 Name: category, dtype: int64)

In [68]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [69]:
model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=500)
model.fit(x_train,y_train)

c:\Users\USER001\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=500, multi_class='multinomial')

In [70]:
y_pred  = model.predict(x_test)
accuracy_score(y_test,y_pred)*100

100.0