In [17]:
import torch
import torch.version
import numpy as np


תרגיל 1: יצירת טנזור 1D (וקטור)
מטרה: צור טנזור בגודל 1D עם המספרים [1, 2, 3, 4, 5].

In [7]:
vactor = torch.tensor([1,2,3,4,5])
vactor

tensor([1, 2, 3, 4, 5])

תרגיל 2: יצירת טנזור 2D (מטריצה)
מטרה: צור מטריצה בגודל 2x3 עם ערכים שלמים.

In [9]:
matrix = torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

תרגיל 3: יצירת טנזור מסוג float
מטרה: צור טנזור עם ערכים ממשיים (float).

python
Copy
Edit


In [10]:
float_val = torch.tensor([1,2,4],dtype=torch.float32)
float_val

tensor([1., 2., 4.])

תרגיל 4: יצירת טנזור מאינדקסים באמצעות range
מטרה: צור טנזור שמכיל את הערכים מ-0 עד 9.

In [12]:
tansor_range = torch.arange(1,9)
tansor_range

tensor([1, 2, 3, 4, 5, 6, 7, 8])

תרגיל 5: יצירת טנזור של אפסים ואחדים
מטרה: השתמש ב-torch.zeros() ו-torch.ones() ליצירת טנזורים.

In [13]:
ones = torch.ones(10)
zeros = torch.zeros(10)
ones,zeros

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

תרגיל 6: יצירת טנזור עם ערכים רנדומליים
מטרה: צור טנזור בגודל 3x3 עם ערכים רנדומליים בין 0 ל-1.

In [15]:
rand = torch.rand(3,3)
rand

tensor([[0.0658, 0.7686, 0.7352],
        [0.0757, 0.0975, 0.1796],
        [0.3684, 0.0386, 0.1794]])

תרגיל 7: המרת טנזור ל-NumPy ולהפך
מטרה: המר בין טנזור למערך NumPy.

In [21]:
arr = np.random.randint(1,50,(5,4))
from_numpy = torch.from_numpy(arr)
from_numpy

back_numpy =from_numpy.numpy()
type(back_numpy),type(from_numpy)

(numpy.ndarray, torch.Tensor)

תרגיל 8: שיבוץ ערכים בטנזור
מטרה: צור טנזור ושנה את הערך בתא מסוים.

In [28]:
from_numpy[3][2] = 14
from_numpy

tensor([[11, 27, 48, 38],
        [ 2,  2, 39, 20],
        [25, 30, 12,  3],
        [13, 10, 14, 13],
        [ 2, 25, 38, 44]], dtype=torch.int32)

תרגיל 10: יצירת טנזור עם ערכים לינאריים
מטרה: צור טנזור עם ערכים מ-0 עד 1 עם צעד של 0.2.

In [29]:
tensor_step = torch.arange(0,1,0.2)
tensor_step

tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000])

תרגיל 11: שינוי סוג נתונים של טנזור

In [32]:
tensor_type = torch.arange(1,12)
tensor_type.to(torch.float32)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

תרגיל 11: שינוי סוג נתונים של טנזור

In [35]:
x = torch.tensor([[1,2],[3,4],[4,6]])
like_tensor = torch.zeros_like(x)
like_tensor

tensor([[0, 0],
        [0, 0],
        [0, 0]])

תרגיל 13: חישוב ממוצע, סכום, מקסימום ומינימום בטנזור
מטרה: הפעל פונקציות סטטיסטיות בסיסיות על טנזור.


In [37]:
func_tensor = torch.randint(1,30,size=(4,6))
func_tensor

tensor([[ 2,  7, 28,  4,  9, 10],
        [23, 17, 17, 20, 17, 10],
        [21, 14, 11,  2, 29,  1],
        [18, 14, 26,  1, 16, 12]])

In [42]:
func_tensor.sum(),func_tensor.min(),func_tensor.max(),func_tensor.mean(dtype=torch.float16),func_tensor.median()

(tensor(329),
 tensor(1),
 tensor(29),
 tensor(13.7109, dtype=torch.float16),
 tensor(14))

תרגיל 14: שינוי צורת טנזור (reshape)
מטרה: הפוך טנזור בגודל 6 ל-2x3.

In [46]:
tensor_reshape = torch.tensor([1,2,3,4,5,6])
torch.reshape(tensor_reshape,(3,2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])

תרגיל 15: חיבור וחיסור בין טנזורים
מטרה: בצע פעולות מתמטיות על טנזורים בעלי אותה צורה.


In [47]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

a+b,b-a

(tensor([5, 7, 9]), tensor([3, 3, 3]))

תרגיל 16: מכפלה מטריציונית (matmul)
מטרה: בצע כפל מטריצות בגודל מתאים.

In [ ]:
a1 = torch.tensor([[1,2],
                   [3,4]])
a2 = torch.tensor([[5,6],
                   [3,4]])

a1,a2,torch.matmul(a1,a2)


(tensor([[1, 2],
         [3, 4]]),
 tensor([[5, 6],
         [3, 4]]),
 tensor([[11, 14],
         [27, 34]]))

In [53]:
1*5+2*3 ,1*6+2*4 ,3*5+4*3, 3*6+4*4 ## example

(11, 14, 27, 34)

תרגיל 17: אינדוקס וחיתוך טנזור
מטרה: שלוף אלמנטים מתוך טנזור.

In [70]:
tensor_pull = torch.tensor([[10,20],[40,50],[78,65]])
tensor_pull,tensor_pull[1][1],tensor_pull[1,1],tensor_pull[:,1]

(tensor([[10, 20],
         [40, 50],
         [78, 65]]),
 tensor(50),
 tensor(50),
 tensor([20, 50, 65]))

תרגיל 18: קיבוץ טנזורים עם torch.cat
מטרה: חבר טנזורים לאורך ציר מסוים.

In [74]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

concat_0 = torch.cat((a, b), dim=0)  # ציר 0 – הוספת שורות
concat_1 = torch.cat((a, b), dim=1)  # הוספת עמודות

concat_0,concat_1

(tensor([[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]),
 tensor([[1, 2, 5, 6],
         [3, 4, 7, 8]]))

תרגיל 19: סידור מחדש של אלמנטים (view / reshape)
מטרה: שנה את הטנזור ל-3 מימדים בגודל 2x1x3

In [78]:
a = torch.tensor([1,2,3,4,5,6])

res = a.view(2,3,1)
res

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]])

תרגיל 20: יצירת טנזור עם ערכים קבועים
מטרה: צור טנזור בגודל 4x4 עם הערך 7 בכל תא.


In [80]:
full_tensor = torch.full((4,6),7)
full_tensor

tensor([[7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7, 7]])

תרגיל 21: שימוש ב־requires_grad=True לחישוב גרדיאנט
מטרה: צור טנזור שמאפשר חישוב נגזרת אוטומטית.

In [87]:
x = torch.tensor([2.0], requires_grad=True)
y = x**3 + 2*x + 1

y.backward()
print("Gradient:", x.grad) 

Gradient: tensor([14.])


תרגיל 22: השוואה בין טנזורים (==, >, logical_and)
מטרה: השווה בין ערכים של טנזור או בין שניים.



In [94]:
tensor1 = torch.tensor([4,5,6,6,7])
tensor2 = torch.tensor([2,5,2,7,2])

equal = tensor1>tensor2
equal

tensor([ True, False,  True, False,  True])

תרגיל 23: מיון (Sorting) של טנזור
מטרה: מיין טנזור בסדר עולה וירד.

In [95]:
sort,indicate = torch.sort(tensor1)
sort,indicate

(tensor([4, 5, 6, 6, 7]), tensor([0, 1, 2, 3, 4]))

תרגיל 24: שימוש בפונקציית clamp להגבלת ערכים
מטרה: הגבל ערכים של טנזור לתחום מסוים (למשל 0–1).

In [96]:
limit = torch.clamp(tensor1,min=4,max=6)
limit

tensor([4, 5, 6, 6, 6])

תרגיל 25: שימוש בפונקציות מתמטיות (sin, log, exp)
מטרה: הפעל פונקציות מתמטיות על טנזור.

In [97]:
x = torch.tensor([0.0, torch.pi / 2, torch.pi])

print("Sin:", torch.sin(x))
print("Log:", torch.log(torch.tensor([1.0, 2.0, 3.0])))
print("Exp:", torch.exp(torch.tensor([0.0, 1.0])))

Sin: tensor([ 0.0000e+00,  1.0000e+00, -8.7423e-08])
Log: tensor([0.0000, 0.6931, 1.0986])
Exp: tensor([1.0000, 2.7183])


תרגיל 27: יצירת טנזור עם ערכים אקראיים נורמליים
מטרה: צור טנזור עם התפלגות נורמלית (Gaussian).

In [98]:
xy = torch.randn(4,4)
xy

tensor([[-0.5477,  0.0102, -1.2630,  0.7197],
        [ 0.9760,  0.0259,  1.0152,  2.0255],
        [ 0.2883, -0.2260, -1.8247,  0.3103],
        [ 0.3696, -0.1485, -1.4134,  0.3873]])

In [100]:
## דוגמא נוספת
mean = 5
std =3
xy2 = torch.randn(4,4)*std + mean
xy2

tensor([[ 4.7277,  8.9883, 11.4614,  5.8984],
        [ 4.3918,  7.0453,  3.5954,  9.9708],
        [ 6.6216, -0.5026, 10.3934,  7.2729],
        [ 9.3947, 10.2040,  6.1814,  8.8426]])

In [101]:
# דוגמא שונה
xy3 = torch.empty(4, 4).uniform_(2, 8)
xy3

tensor([[3.3940, 7.2870, 3.5469, 4.1362],
        [6.8408, 5.8983, 7.8331, 6.8048],
        [6.2966, 3.5183, 5.0739, 4.9989],
        [5.3663, 6.5666, 6.1870, 2.1818]])

תרגיל 28: מציאת אינדקס הערך המקסימלי (argmax)
מטרה: מצא את מיקום הערך הכי גבוה בטנזור.


In [102]:
tensor = torch.tensor([34,66,11,88,52])

torch.argmax(tensor)

tensor(3)

תרגיל 29: נורמליזציה של טנזור (לערכים בין 0 ל־1)
מטרה: הפוך ערכים בטנזור כך שיישרו לקנה מידה 0–1.

In [104]:
n_norm = (tensor - tensor.min()) / (tensor.max() - tensor.min())
n_norm

tensor([0.2987, 0.7143, 0.0000, 1.0000, 0.5325])

תרגיל 30: שימוש ב־masked_fill לעבודה עם מסיכות
מטרה: החלף ערכים בטנזור לפי מסיכה.

In [108]:
x = torch.tensor([1.0, 2.0, 3.0,43.0,55.0])

mask = x >3

res =  x.masked_fill(mask, value=0)
res

tensor([1., 2., 3., 0., 0.])